version: "3.7"

services:
  luxcar_database:
    image: postgres
    container_name: luxcar_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=luxcar
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=luxcar
    volumes:
      - pgdata:/data/postgres
  luxcar_app:
    build: .
    container_name: luxcar_app
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links: 
      - luxcar_database
    depends_on:
      - luxcar_database

volumes:
  pgdata:
    driver: local
