version: "3.7"

services:
  database_luxcar:
    image: postgres
    container_name: database_luxcar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=luxcar
    volumes:
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: luxcar
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database_luxcar
    depends_on:
      - database_luxcar


volumes:
  pgdata:
    driver: local
